//! Common LLM provider trait.
//!
//! All LLM backends implement this trait to provide a uniform interface
//! for chat completion with tool calling and streaming support.

use crate::llm::{ChatMessage, LlmResponse, StreamEvent, ToolDefinition};
use async_trait::async_trait;
use futures::stream::BoxStream;

/// Trait that all LLM providers must implement.
///
/// The mock (generated by mockall) is compiled unconditionally so that
/// integration tests in `tests/` can use `MockLlmProvider`.
#[mockall::automock]
#[async_trait]
pub trait LlmProvider: Send + Sync {
    /// Send a chat completion request to the LLM.
    ///
    /// # Arguments
    /// - `messages`: The conversation history
    /// - `tools`: Available tool definitions for the model to call
    ///
    /// # Returns
    /// The model's response, potentially including tool calls.
    async fn chat(
        &self,
        messages: &[ChatMessage],
        tools: &[ToolDefinition],
    ) -> anyhow::Result<LlmResponse>;

    /// Stream a chat completion as token deltas.
    ///
    /// Providers without native streaming fall back to [`Self::chat`]
    /// and emit the whole response as a single `TextDelta` + `Done`.
    async fn chat_stream(
        &self,
        messages: &[ChatMessage],
        tools: &[ToolDefinition],
    ) -> anyhow::Result<BoxStream<'static, anyhow::Result<StreamEvent>>> {
        let response = self.chat(messages, tools).await?;
        let mut events = Vec::new();
        if !response.content.is_empty() {
            events.push(Ok(StreamEvent::TextDelta(response.content.clone())));
        }
        events.push(Ok(StreamEvent::Done(response.finish_reason)));
        Ok(Box::pin(futures::stream::iter(events)))
    }

    /// Get the provider name (e.g., "openai", "anthropic").
    fn name(&self) -> &str;

    /// Validate that the provider is properly configured.
    fn validate(&self) -> anyhow::Result<()>;
}
